[icons]
icons = "awesome4"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "backlight"
missing_format = ""

[[block]]
block = "sound"
max_vol = 100

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%A %-d.%-m.%Y %H:%M:%S') "

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"
