[icons]
icons = "material-nf"

[theme.overrides]
idle_bg = "#1e1e2e"
idle_fg = "#cdd6f4"
info_bg = "#1e1e2e"
info_fg = "#cdd6f4"
good_bg = "#1e1e2e"
good_fg = "#cdd6f4"
warning_bg = "#1e1e2e"
warning_fg = "#cdd6f4"
critical_bg = "#1e1e2e"
critical_fg = "#cdd6f4"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"

[[block]]
block = "disk_space"
if_command = "hostname | grep -q 'jolepc'"
format = " / $icon $available "

[[block]]
block = "disk_space"
if_command = "hostname | grep -q 'jolelaptop'"
format = " / $icon $available "

[[block]]
block = "disk_space"
if_command = "hostname | grep -q 'jolepc'"
format = " /mnt/ssd $icon $available "
path = "/mnt/ssd"

[[block]]
block = "disk_space"
if_command = "hostname | grep -q 'jolepc'"
format = " /mnt/hdd $icon $available "
path = "/mnt/hdd"

[[block]]
block = "backlight"
if_command = "hostname | grep -q 'jolelaptop'"

[[block]]
block = "sound"
max_vol = 100
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
if_command = "hostname | grep -q 'jolelaptop'"

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%A %-d.%-m.%Y %H:%M:%S') "

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |} "
