[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "pacman"
signal = 1
interval = 600
error_interval = 300
format = " $icon $pacman + $aur = $both updates available "
format_singular = " $icon $both update available "
format_up_to_date = " $icon system up to date "
critical_updates_regex = "linux"
aur_command = "yay -Qua"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "backlight"
missing_format = ""

[[block]]
block = "sound"
driver = "alsa"
format = " $icon $output_description {$volume.eng(w:2)|} "
step_width = 3
max_vol = 100
natural_mapping = true

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%A %-d.%-m.%Y %H:%M:%S') "

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"
