[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "backlight"
missing_format = ""

[[block]]
block = "sound"
max_vol = 100
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%A %d.%B.%Y %H:%M:%S') "

