[icons]
icons = "awesome4"

[[block]]
block = "disk_space"

[[block]]
block = "backlight"
missing_format = ""

[[block]]
block = "sound"
max_vol = 100
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%A %-d.%-m.%Y %H:%M:%S') "

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"
